[workspace]
members = [
    "api-dpm",
    "api-gate",
    "api-picboo",
    "api-artifactory",
    "api-nexus",
    "api-release",
    "cli-common",
    "static-remote"
    ]
resolver = "2"  # 推荐使用较新的解析器
